### PR TITLE
Support subscriptions

### PR DESCRIPTION
**Pull request by Hugome**
Respond of #3 

I try something for subscriptions support, it's not perfect and i think these can be improve : 
 - The fact that payload is "Bouncing" from local PubSub (Maybe using events instead of broker.call to emit payload, and create some magic asyncIterator ?)
 - The filter function is heavy just for filtering (One action for that...)

I'm open to critics and help before any merge :)

### CODE REVIEW

**Comment by icebob** [comment]
Good job @Hugome!
Is there any reason why you use broker.call for publishing? I think a broadcast event could be better because if you have multiple API gateways instances it must be reached all instances and all subscription clients, right?

**Comment by Hugome** [comment]
@icebob Your right (I was hesitant between call and events, and you give the right reason to choose events :))
Changes done

**Comment by icebob** [comment]
Great! I will check.

**Comment by icebob** [comment]
Thanks @faeron, all tests are missing in this repo :) This is the reason why it is not published on NPM yet.

**Pull request merged**
